<div class="content">
    <h1 class="page-title"><?=__t(end($pagePath));?></h1>
    <?php if(!empty($formData['errors'])): ?>
    <div class="form-errors">
        <ul>
            <?php foreach ($formData['errors'] as $formError): ?>
            <li><?=__t($formError);?></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <dir class="clear"></dir>
    <?php endif; ?>
    <form action="<?=$formAction;?>" method="POST">
        <div>
            <input type="text"
                   name="title"
                   placeholder="<?=__t('Title');?>"
                   value="<?=$formData['title'];?>">
        </div>
        <div>
            <input type="text"
                   name="slug"
                   placeholder="<?=__t('Slug');?>"
                   value="<?=$formData['slug'];?>">
        </div>
        <?php if(!empty($categories)): ?>
        <div>
            <select name="id_parent">
                <?php if (empty($formData['id_parent'])): ?>
                <option disabled selected>
                    <?=__t('Select Parent Category');?>
                </option>
                <?php else: ?>
                <option disabled><?=__t('Select Parent Category');?></option>
                <?php endif; ?>
                <?php foreach ($categories as $category): ?>
                    <?php
                        if (
                            isset($currentCategoryId) &&
                            $category->getId() == $currentCategoryId
                        ) {
                            continue;
                        }
                    ?>
                    <?php if ($category->getId() == $formData['id_parent']): ?>
                <option value="<?=$category->getId();?>" selected>
                    <?=__t($category->getTitle());?>
                </option>
                    <?php else: ?>
                <option value="<?=$category->getId();?>">
                    <?=__t($category->getTitle());?>
                </option>
                    <?php endif; ?>
                <?php endforeach;?>
            </select>
        </div>
        <?php endif; ?>
        <div>
            <input type="submit" value="<?=__t('Save');?>">
        </div>
        <dir class="clear"></dir>
    </form>
</div>
    