<div class="ajax-wrapper">
    <h1 class="ajax-title"><?=$file->getTitle();?></h1>
    <div class="ajax-file-wrapper">
        <img src="<?=$file->getPreviewPath();?>" class="file-preview">
        <div class="file-links">
            <img src="<?=$file->getQrPath();?>" class="file-qr">
            <a href="<?=$file->getFilePath();?>"
               target="_blank"
               class="file-link-view">
                <span>
                    <i class="fa fa-eye" aria-hidden="true"></i>
                </span>
                <?=__t('Read');?>
            </a>
            <a href="<?=$file->getFilePath();?>"
               target="_blank"
               class="file-link-download"
               download>
                <span>
                    <i class="fa fa-download" aria-hidden="true"></i>
                </span>
                <?=__t('Download');?>
            </a>
            <div class="ajax-views">
                <?=__t('Views');?>: <?=$file->getViews();?>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>