<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<meta name="keywords" content="<?=__t($meta['keywords']);?>">
<meta name="description" content="<?=__t($meta['description']);?>">

<meta property="og:url" content="<?=$meta['canonical_url'];?>" />
<meta property="og:site_name" content="<?=__t($meta['site_name']);?>" />
<meta property="og:image" content="<?=$meta['image'];?>" />

<meta property="og:description" content="<?=__t($meta['description']);?>" />
<meta property="og:locale" content="<?=$meta['locale'];?>" />
<meta property="og:type" content="article" />

<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@<?=$meta['twitter'];?>" />
<meta name="twitter:description" content="<?=__t($meta['description']);?>" />
<meta name="twitter:image" content="<?=$meta['image'];?>" />

<?php if (isset($seoTitle) && !empty($seoTitle)): ?>
<meta property="og:title" content="<?=__t($seoTitle);?>" />
<meta name="twitter:title" content="<?=__t($seoTitle);?>" />
<?php
    else:
?>
<meta property="og:title" content="<?=__t($meta['title']);?>" />
<meta name="twitter:title" content="<?=__t($meta['title']);?>" />
<?php endif; ?>

<meta name="theme-color" content="#476C9B">
